name: blog_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flare_flutter:
  curved_navigation_bar:
  firebase_database:
  intl: ^0.15.8
  toast: ^0.1.5
  liquid_progress_indicator: 0.3.2
  firebase_auth: 0.14.0+5
  firebase_storage: 3.0.4
  google_fonts: ^1.1.0
  image_picker: 0.6.0+17
  velocity_x: ^0.4.1

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Filip.flr
    - assets/Animals.flr

  fonts:
    - family: Open
      fonts:
        - asset: font/OpenSans-SemiBold.ttf
          weight: 600
